### ISSUE TITLE
 Unable to find the file '/provision/main/etc/hosts.json'

### ISSUE THREAD

**Issue by ghost** [mdkholy/dashbrew#10]
I get this error after a clean recurisive clone and a vagrant up, no records are added to my hosts file, adding 192.168.10.10 dashbrew.dev manually still doesn't work. 

I'm on Win64 / Virtualbox 4.3.24 / Vagrant 1.7.2 w/ hosts provisioner plugin and vagrant-vbguest plugin installed.

Any help is much appriciated.

**Comment by ghost** [comment]
The problem was actaully due to provisioning not running due to a dodgy characters in the shell script from windows git convering EOLs. Setting git config --global core.autocrlf false solved the problem for me.

**Comment by JohnHeroHD** [comment]
I'm gacing the same issue, and running the command "git config --global core.autocrlf false" did not solve the issue.

I deleted the repo and cloned it again after setting the global config.

Here is the complete output:

`Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'mdkholy/dashbrew'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'mdkholy/dashbrew' is up to date...
==> default: Setting the name of the VM: dashbrew_default_1426666597615_36070
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2200 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if its present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /var/www => C:/dashbrew/public
    default: /vagrant => C:/dashbrew
==> default: Running provisioner: shell...
    default: Running: C:/Users/John/AppData/Local/Temp/vagrant-shell20150318-6016-1p0i3ze.sh
==> default: stdin: is not a tty
==> default: /tmp/vagrant-shell: /vagrant/provision/main/dashbrew: /usr/bin/php^M: bad interpreter: No such file or dire
ctory
==> default: Running provisioner: hostsupdate...
==> default: Updating hosts file on the guest machine...
==> default: Unable to find the file '/provision/main/etc/hosts.json'
==> default: '/etc/hosts' file updated successfully
==> default: Updating hosts file on the host machine (password may be required)...
==> default: Unable to find the file '/provision/main/etc/hosts.json'
==> default: 'C:\Windows\System32\drivers\etc\hosts' file updated successfully
PS C:\dashbrew> git config --global core.autocrlf
false`

**Comment by chillyistkult** [comment]
It's still not working on Windows 7 Vagrant 1.7.2 

```
==> default: Updating hosts file on the host machine (password may be required)...
==> default: Unable to find the file '/provision/main/etc/hosts.json'
==> default: 'C:\Windows\System32\drivers\etc\hosts' file updated successfully
```
