### ISSUE TITLE
View-Button on Dashboard not working on Firefox Dev

### ISSUE THREAD

**Issue by te-gpm** [mdkholy/dashbrew#16]
The view button next to my recent projects that is supposed to trigger a js popup does not work in current firefox versions (ubuntu 14.10, current firefox-dev). It redirects to a blank page with the URL 'javascript:$.openProjectInfo('/projects/info/dashbrew.dev');' and the content [object Object]. Popup works fine in chrome though.

Surely not the highest priority, but wanted to let you know anyway ;)

Great work, love this vagrant box! :)

**Comment by mohatt** [comment]
Fixed in #20
