### ISSUE TITLE
Missing Wiki

### ISSUE THREAD

**Issue by Bogardo** [mdkholy/dashbrew#17]
There are a number of references in the README to a wiki page. But the wiki doesn't seem to exist.

**Comment by mohatt** [comment]
I am still working on the wiki and it will be available very soon. Thank you :-)

**Comment by colinodell** [comment]
+1

**Comment by jkenneydaniel** [comment]
Not trying to be a pest - but it's been over a month - don't really understand why this issue was closed when the Wiki still isn't available. Pretty valid issue IMO.

**Comment by imakarov** [comment]
+1

**Comment by colinodell** [comment]
+1

**Comment by wdmtech** [comment]
+1

**Comment by XedinUnknown** [comment]
+1
