### ISSUE TITLE
Solution for projects that are built dynamically which deletes the .dashbrew file

### ISSUE THREAD

**Issue by crittermike** [mdkholy/dashbrew#41]
For example, I have a projects that needs to be rebuilt on a regular basis, meaning that placing a .dashbrew in the site root will only work temporarily until it gets removed by the next rebuild.

Is there an alternative for this? Perhaps a global .dashbrew file that allows me to specify where the root directory lives for each project, instead of having to put the file in the root directory?

**Comment by ghost** [comment]
There should be a .dashbrew file in the public directory that lets you do this. The one that contains the vhosts for phpmyadmin, monit and mailcatcher

**Comment by crittermike** [comment]
@edhardie that's perfect, never realized that. Thanks!
