### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by frdmn** [mdkholy/dashbrew#46]
Hi Mohamed,

I would like to know if we can expect updates in the future or if you've stopped working on it. 

Thanks,
Jonas

**Comment by gebeer** [comment]
+1

**Comment by maxdmyers** [comment]
+1

**Comment by davtech** [comment]
+1

**Comment by frdmn** [comment]
bump 

/cc @mdkholy

**Comment by mohatt** [comment]
Please see the updated README.md
